"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${time.strftime('%Y-%m-%d %H:%M:%S')}
"""

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Flask-Migrate - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Flask-Migrate - please adjust! ###
    pass
    # ### end Alembic commands ###

